pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Test Completed') {
            steps {
                echo "Test Completed"
            }
        }
        stage('Complete') {
            steps {
                echo "Job Completed!"
            }
        }
    }
}
